#pragma once;
#include<SFML/Graphics.hpp>
#include<SFML/Audio.hpp>
#include<bits/stdc++.h>
using namespace std;
using namespace sf;
class game
{
public:
    game(float width,float height);
    ~game();
    void updatePlayer(char c);
    void draw(RenderWindow& window);
    bool in_bound(float x,float y,Sprite sprite);
    void run_star1();
    void run_star2();
    void run_star3();
    void run_kata1();
    void run_kata2();
    void run_kata3();
    void run();
    void player_animation(RenderWindow& Window);
    Vector2f pos;
    Texture arrowTexture;
    Sprite arrowSprite;
    Texture BgTexture;
    Sprite BgSprite;
    Texture PlTexture;
    Sprite PlSprite;
    Texture obsTexture;
    Sprite obsSprite;
    Texture obs1Texture;
    Sprite obs1Sprite;
    Texture obs2Texture;
    Sprite obs2Sprite;
    Texture wallTexture;
    Sprite wallSprite;
    Texture wall2Texture;
    Sprite wall2Sprite;
    Texture wall3Texture;
    Sprite wall3Sprite;
    Texture wall4Texture;
    Sprite wall4Sprite;
    Texture wall5Texture;
    Sprite wall5Sprite;
    Texture wall6Texture;
    Sprite wall6Sprite;
    Texture wall7Texture;
    Sprite wall7Sprite;
    Texture wall8Texture;
    Sprite wall8Sprite;
    Texture wall9Texture;
    Sprite wall9Sprite;
    Texture wall10Texture;
    Sprite wall10Sprite;
    Texture kataTexture;
    Sprite kataSprite;
    Texture kata2Texture;
    Sprite kata2Sprite;
    Texture kata3Texture;
    Sprite kata3Sprite;
    Texture kboxTexture;
    Sprite kboxSprite;
    Texture kbox2Texture;
    Sprite kbox2Sprite;
    Texture kbox3Texture;
    Sprite kbox3Sprite;
    Texture kbox4Texture;
    Sprite kbox4Sprite;
    Texture kbox5Texture;
    Sprite kbox5Sprite;
    Texture menuBgTexture;
    Sprite menuBgSprite;
    float aclr;
    float w_width,w_height;
    float a,b;
    float a1,b1;
    float a2,b2;
    float a3,b3;
    float a4,b4;
    float a5,b5;
    bool chk;
    bool chk1;
    bool chk2;
    bool chk3;
    bool chk4;
    bool chk5;
    bool is_right;
    bool is_left;
    bool is_up;
    bool is_down;
    bool is_running;
    bool is_game_over;
    bool is_pause;
    bool is_resume;
    bool you_win=0;
    bool is_home=1;
};
